version: '3'

volumes:
  pg_data_production:
  media:
  static:

services:
  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: on-failure
  backend:
    image: levtigrovich/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/app/foodgram/static_backend/
      - media:/app/foodgram/media_backend/
    restart: on-failure
    depends_on:
      - db
  frontend:
    image: levtigrovich/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
    restart: on-failure
    depends_on:
      - backend

  nginx:
    image: levtigrovich/foodgram_nginx:latest
    env_file: .env
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media:/usr/share/nginx/html/media_backend/
      - static:/usr/share/nginx/html/static_backend/
    ports:
      - ${GATEWAY_PORT}
    restart: on-failure
