version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/foodgram/static_backend/
      - media:/app/foodgram/media_backend/
      - ../data/:/app/data/
    restart: on-failure

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    restart: on-failure

  nginx:
    image: nginx:1.19.3-alpine
    env_file: .env
    ports:
      - ${GATEWAY_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html/static_backend/
      - media:/usr/share/nginx/html/media_backend/
    restart: on-failure
    depends_on:
      - backend